/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SubWallets } from "./SubWallets";
export * as factories from "./factories";
export { SubWallets__factory } from "./factories/SubWallets__factory";
